### ISSUE TITLE
structure.create_atom_names no longer accepts list of strings

### ISSUE THREAD

**Issue by jnwei** [biotite-dev/biotite#915]
### Description:

Hi, thanks for the great work with biotite!

The change to `create_atom_names` in (#897) causes the allowed inputs of this function to be limited to `AtomArray` and `AtomArrayStack`. 

Previously `create_atom_names` accepted a plain list of strings representing atom names. This functionality is useful when creating a molecule directly from an rdkit molecule or smiles, without needing to generate an `AtomArrayStack` first. One use case of this behavior is in the openfold-3 repo [example here](https://github.com/aqlaboratory/openfold-3/pull/274/changes#diff-975fc0a76594394c54ca4322e8483f74c6d3ba9c6d367173353e0f851184a5aeL223).

### Minimal example

```python
elements = ["C", "C", "O"]
# works in 1.6
# fails in 1.7 with 
# `AttributeError: 'list' object has no attribute 'array_length'`
new_elements = structure.create_atom_names(elements)

# Creating an AtomArrayStack works instead
mol = Chem.MolFromSmiles("CCO") 
test_array = rdkit_interface.from_mol(mol)
new_elements = structure.create_atom_names(test_array)
```

### Suggested fix

Add a small type check to get the length of `atoms` in [`create_atom_names`](https://github.com/padix-key/biotite/blob/4e270a94502de239149857679e6a9191b7f92e59/src/biotite/structure/repair.py#L147-L150), e.g.

```python
    if isinstance(atoms, list):
        atom_len = len(atoms)
    elif isinstance(atoms, (struc.AtomArray, struc.AtomArrayStack)):
        atom_len = atoms.array_length()

    if atom_len == 1:
       return elements.astype("U6")
```

### Related issue
https://github.com/aqlaboratory/openfold-3/pull/274

**Comment by padix-key** [comment]
Thanks for reporting! You are right, this was an oversight in #897.

**Comment by jnwei** [comment]
Thank you so much for the quick fix!
